server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: user-api
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/user/**
                - id: activity-api
                  uri: http://localhost:8082/
                  predicates:
                      - Path=/activity/**
                - id: shopping-api
                  uri: http://localhost:8083/
                  predicates:
                      - Path=/shopping/**