server:
    servlet:
        encoding:
            force-response: 'true'
        context-path: /shopping
    port: 8083


spring:
    profiles:
        include: secret
    devtools:
        restart:
            enabled: 'true'
        livereload:
            enabled: 'true'
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mycat_shopping?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                connection:
                    characterEncoding: utf-8
                    charSet: UTF-8
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
    redis:
        host: localhost
        port: 6379

#logging:
#    level:
#        org.springframework: DEBUG
